package server
import("encoding/json";"net/http";"strconv";"github.com/stockyard-dev/stockyard-roundup/internal/store")
func(s *Server)handleListMeetings(w http.ResponseWriter,r *http.Request){list,_:=s.db.ListMeetings();if list==nil{list=[]store.Meeting{}};writeJSON(w,200,list)}
func(s *Server)handleGetMeeting(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);m,err:=s.db.GetMeeting(id);if err!=nil{writeError(w,404,"not found");return};writeJSON(w,200,m)}
func(s *Server)handleCreateMeeting(w http.ResponseWriter,r *http.Request){var m store.Meeting;json.NewDecoder(r.Body).Decode(&m);if m.Title==""||m.Date==""{writeError(w,400,"title and date required");return};if m.Duration==0{m.Duration=60};if err:=s.db.CreateMeeting(&m);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,m)}
func(s *Server)handleUpdateNotes(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);var req struct{Notes string `json:"notes"`};json.NewDecoder(r.Body).Decode(&req);s.db.UpdateMeetingNotes(id,req.Notes);writeJSON(w,200,map[string]string{"status":"updated"})}
func(s *Server)handleDeleteMeeting(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteMeeting(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleListActions(w http.ResponseWriter,r *http.Request){midStr:=r.URL.Query().Get("meeting_id");mid,_:=strconv.ParseInt(midStr,10,64);open:=r.URL.Query().Get("open")=="1";list,_:=s.db.ListActionItems(mid,open);if list==nil{list=[]store.ActionItem{}};writeJSON(w,200,list)}
func(s *Server)handleCreateAction(w http.ResponseWriter,r *http.Request){var a store.ActionItem;json.NewDecoder(r.Body).Decode(&a);if a.Description==""{writeError(w,400,"description required");return};if err:=s.db.CreateActionItem(&a);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,a)}
func(s *Server)handleToggleAction(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.ToggleActionItem(id);writeJSON(w,200,map[string]string{"status":"toggled"})}
func(s *Server)handleDeleteAction(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteActionItem(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleStats(w http.ResponseWriter,r *http.Request){m,_:=s.db.CountMeetings();a,_:=s.db.CountOpenActions();writeJSON(w,200,map[string]interface{}{"meetings":m,"open_actions":a})}
