package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Roundup</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:.5rem;flex-wrap:wrap;align-items:center}.toolbar select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.task-row{display:flex;align-items:center;gap:.5rem;padding:.4rem .5rem;border-bottom:1px solid var(--bg3);font-size:.75rem}.task-check{cursor:pointer;font-size:.8rem}.task-title{flex:1}.task-title.done{text-decoration:line-through;color:var(--cm)}.pri{font-size:.55rem;padding:.05rem .25rem;border:1px solid;border-radius:2px}.pri-urgent{border-color:var(--red);color:var(--red)}.pri-high{border-color:var(--rl);color:var(--rl)}.pri-medium{border-color:var(--gold);color:var(--gold)}.pri-low{border-color:var(--cm);color:var(--cm)}.task-assignee{font-size:.6rem;color:var(--leather)}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=date],textarea,select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:60px}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Roundup</span></h1><button class="btn btn-p" onclick="showNew()">+ Task</button></div>
<div class="main"><div class="overview" id="ov"></div>
<div class="toolbar"><select id="stFilter" onchange="load()"><option value="">All</option><option value="todo">Todo</option><option value="in_progress">In Progress</option><option value="done">Done</option></select><select id="priFilter" onchange="load()"><option value="">All priorities</option><option>urgent</option><option>high</option><option>medium</option><option>low</option></select></div>
<div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function init(){const sd=await api('/api/stats');document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.todo+'</b>Todo</div><div class="stat"><b>'+sd.in_progress+'</b>In Progress</div><div class="stat"><b style="color:var(--green)">'+sd.done+'</b>Done</div><div class="stat"><b>'+sd.projects+'</b>Projects</div>';load()}
async function load(){const p=new URLSearchParams();const st=document.getElementById('stFilter').value;if(st)p.set('status',st);const pr=document.getElementById('priFilter').value;if(pr)p.set('priority',pr)
const d=await api('/api/tasks?'+p);const tasks=d.tasks||[];
document.getElementById('list').innerHTML=tasks.length?tasks.map(t=>'<div class="task-row"><span class="task-check" onclick="toggle(\''+t.id+'\',\''+(t.status==='done'?'todo':'done')+'\')">'+(t.status==='done'?'☑':'☐')+'</span><span class="task-title '+(t.status==='done'?'done':'')+'">'+esc(t.title)+'</span><span class="pri pri-'+t.priority+'">'+t.priority+'</span>'+(t.assignee?'<span class="task-assignee">'+esc(t.assignee)+'</span>':'')+(t.due_date?'<span style="font-size:.6rem;color:var(--cm)">'+t.due_date+'</span>':'')+'<span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="del(\''+t.id+'\')">del</span></div>').join(''):'<div class="empty">No tasks. Add one to get started.</div>'}
async function toggle(id,status){await api('/api/tasks/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});load();init()}
async function del(id){await api('/api/tasks/'+id,{method:'DELETE'});load();init()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Task</h2><label class="fl">Title</label><input type="text" id="nt-title"><label class="fl">Description</label><textarea id="nt-desc" rows="2"></textarea><div class="form-row"><div><label class="fl">Priority</label><select id="nt-pri"><option>medium</option><option>urgent</option><option>high</option><option>low</option></select></div><div><label class="fl">Assignee</label><input type="text" id="nt-assign"></div></div><label class="fl">Due Date</label><input type="date" id="nt-due"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={title:document.getElementById('nt-title').value,description:document.getElementById('nt-desc').value,priority:document.getElementById('nt-pri').value,assignee:document.getElementById('nt-assign').value,due_date:document.getElementById('nt-due').value};if(!b.title){alert('Title required');return};await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load();init()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init()
</script></body></html>`
